[package]
name = "cotton"
version = "0.0.0"
authors = ["Jakub Pastuszek <jpastuszek@protonmail.com>"]
edition = "2018"
description = "A prelude with crates, types and functions useful for writing CLI tools."
repository = "https://github.com/jpastuszek/cotton"
readme = "README.md"
keywords = ["cli", "prelude"]
categories = ["command-line-interface"]
license = "MIT"

[dependencies]
problem = "5.0.0"
structopt = "0.2.12"
log = "0.4.5"
loggerv = { version = "0.7.1", path = "../loggerv" }
boolinator = "2.4.0"
itertools = "0.8.0"
tap = "0.3.1"
