[package]
name = "cotton"
version = "0.0.0-alpha0"
authors = ["Jakub Pastuszek <jpastuszek@protonmail.com>"]
edition = "2018"
description = "A prelude with crates, types and functions useful for writing CLI tools."
repository = "https://github.com/jpastuszek/cotton"
readme = "README.md"
keywords = ["cli", "prelude"]
categories = ["command-line-interface"]
license = "MIT"

[dependencies]
problem = "5.0.0"
structopt = "0.2.12"
log = { version = "0.4.5", features = ["std"] }
boolinator = "2.4.0"
itertools = "0.8.0"
tap = "0.3.1"
ansi_term = "0.11.0"
atty = "0.2.11"

[dev-dependencies]
clap = "2.1.2"