[package]
name = "cotton"
version = "0.0.21-alpha.0"
authors = ["Jakub Pastuszek <jpastuszek@protonmail.com>"]
edition = "2018"
description = "A prelude with crates, types and functions useful for writing CLI tools."
repository = "https://github.com/jpastuszek/cotton"
documentation = "https://docs.rs/cotton"
readme = "README.md"
keywords = ["cli", "prelude"]
categories = ["command-line-interface"]
license = "MIT"

[dependencies]
problem = "5.3.0"
error-context = "0.1.2"
structopt = "0.3.2"
log = { version = "0.4.8", features = ["std"] }
boolinator = "2.4.0"
itertools = "0.9.0"
tap = "1.0.0"
ansi_term = "0.12.1"
atty = "0.2.14"
chrono = "0.4.9"
duct = "0.13.2"
assert_matches = "1.3.0"
linked-hash-map = "0.5.3"
linked_hash_set = "0.1.4"
filetime = "0.2.13"
file-mode = "0.1.2"
scopeguard = "1.1.0"
uninterruptible = "0.1.0"
signal-hook = "0.3.8"
directories = "3.0.2"
maybe-string = "0.1.0"
shellwords = "1.1.0"
secrecy = { version = "0.8.0", features = ["alloc"] }
hex = "0.4.3"
sha2 = "0.9.8"

[target.'cfg(unix)'.dependencies]
exec = "0.3.1"
file-owner = "0.1.0"

[dev-dependencies]
clap = "2.33.0"
